all_split_train: [
  'pevl_gqa_all_split_data.json',
] 
balanced_train: {
  'pevl_gqa_balanced_train_data.json'
}
val_file: [
  'pevl_gqa_balanced_val_data.json'
]
answer_dict_path: ''
image_path: ''

alpha: 0.4
temp: 0.07
vision_width: 768
batch_size: 32
test_batch_size: 32
bert_config: './configs/config_bert.json'
embed_dim: 256
exp_decay_ratio: 0.25
image_res: 256
mlm_probability: 0.35
momentum: 0.995
pos_token_mask_type: 1
postoken_temp: 2
pseudo_normal_ratio: 1
queue_size: 65536
optimizer: {opt: adamW, lr: 2e-5, weight_decay: 0.02}
schedular: {sched: cosine, lr: 2e-5, epochs: 10, min_lr: 1e-6, decay_rate: 1, warmup_lr: 1e-5, warmup_epochs: 5, cooldown_epochs: 0}
