train_vcr_file: ['pevl_vcr_pretrain_data.json'] 
train_val_vcr_q2a_file: ['pevl_vcr_val_QA_data.json']
train_val_vcr_qa2r_file: ['pevl_vcr_val_QAR_data.json']
image_path: '。./chenqianyu/pevl_images'#vcr images root path

alpha: 0.4
temp: 0.07
vision_width: 768
batch_size: 8
test_batch_size: 48
bert_config: './configs/config_bert.json'
embed_dim: 256
exp_decay_ratio: 0.25
image_res: 512
mlm_probability: 0.35
momentum: 0.995
pos_token_mask_type: 1
postoken_temp: 2
pseudo_normal_ratio: 1
queue_size: 65536

optimizer: {opt: adamW, lr: 6e-5, weight_decay: 0.02}
schedular: {sched: cosine, lr: 6e-5, epochs: 6, min_lr: 1e-5, decay_rate: 1, warmup_lr: 1e-5, warmup_epochs: 5, cooldown_epochs: 0}


